### ISSUE TITLE
No such file or directory:fused

### ISSUE THREAD

**Issue by LiZhou-1004** [zq-OwO-qz/Score-based-Generative-Models-with-Adaptive-Momentum#1]
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    import run_lib
  File "/share/home/202310191523/ImageGeneration/run_lib.py", line 29, in <module>
    from models import ddpm, ncsnv2, ncsnpp
  File "/share/home/202310191523/ImageGeneration/models/ncsnpp.py", line 18, in <module>
    from . import utils, layers, layerspp, normalization
  File "/share/home/202310191523/ImageGeneration/models/layerspp.py", line 20, in <module>
    from . import up_or_down_sampling
  File "/share/home/202310191523/ImageGeneration/models/up_or_down_sampling.py", line 10, in <module>
    from op import upfirdn2d
  File "/share/home/202310191523/ImageGeneration/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/share/home/202310191523/ImageGeneration/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/share/home/202310191523/.conda/envs/zqouo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/share/home/202310191523/.conda/envs/zqouo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1534, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/share/home/202310191523/.conda/envs/zqouo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1936, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /share/home/202310191523/.cache/torch_extensions/py38_cu117/fused/fused.so: cannot open shared object file: No such file or directory

Dear author, have you encountered such a problem during the running process.

**Comment by zqOuO** [comment]
Hi JoanNig! I haven't had such a problem before. My main lab environment is on Windows, but I had other issues caused by fused, I solved this by single run ./op/fused_act.py (I think you can try it).  I'm guessing the problem is with the version of the Python environment. I found some similar questions caused by fused, see https://github.com/stanford-crfm/mistral/issues/196.  Hope this works for you.

**Comment by LiZhou-1004** [comment]
> Hi JoanNig! I haven't had such a problem before. My main lab environment is on Windows, but I had other issues caused by fused, I solved this by single run ./op/fused_act.py (I think you can try it). I'm guessing the problem is with the version of the Python environment. I found some similar questions caused by fused, see [stanford-crfm/mistral#196](https://github.com/stanford-crfm/mistral/issues/196). Hope this works for you.

Thank you very much for taking the time to guide me. I tried single run/ op/fused_act.py。 This method did not solve the problem I encountered, I will continue to follow up on the link you recommended to me. Thank you again for your help.

**Comment by zqOuO** [comment]
You are welcome! Similarly, you can try to debug ./op/upfirdn2d.py and check your C compilers, all these 2 Python files use fused and require C++ compilation. I also had a lot of trouble installing the environment when I was using SGM's code.

**Comment by zqOuO** [comment]
> > Hi JoanNig! I haven't had such a problem before. My main lab environment is on Windows, but I had other issues caused by fused, I solved this by single run ./op/fused_act.py (I think you can try it). I'm guessing the problem is with the version of the Python environment. I found some similar questions caused by fused, see [stanford-crfm/mistral#196](https://github.com/stanford-crfm/mistral/issues/196). Hope this works for you.
> 
> Thank you very much for taking the time to guide me. I tried single run/ op/fused_act.py。 This method did not solve the problem I encountered, I will continue to follow up on the link you recommended to me. Thank you again for your help.

You are welcome! Similarly, you can try to debug ./op/upfirdn2d.py and check your C compilers, all these 2 Python files use fused and require C++ compilation. I also had a lot of trouble installing the environment when I was using SGM's code.

**Comment by LiZhou-1004** [comment]
> > > Hi JoanNig! I haven't had such a problem before. My main lab environment is on Windows, but I had other issues caused by fused, I solved this by single run ./op/fused_act.py (I think you can try it). I'm guessing the problem is with the version of the Python environment. I found some similar questions caused by fused, see [stanford-crfm/mistral#196](https://github.com/stanford-crfm/mistral/issues/196). Hope this works for you.
> > 
> > 
> > Thank you very much for taking the time to guide me. I tried single run/ op/fused_act.py。 This method did not solve the problem I encountered, I will continue to follow up on the link you recommended to me. Thank you again for your help.
> 
> You are welcome! Similarly, you can try to debug ./op/upfirdn2d.py and check your C compilers, all these 2 Python files use fused and require C++ compilation. I also had a lot of trouble installing the environment when I was using SGM's code.

Thank you very much. I will try the method you taught me.
